### ISSUE TITLE
Test cases of IntelliJ

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#185]
- [x] Project creation
- [ ] Autocomplete
  - [x] Shows newly added steps within <project>/specs
  - [x] Shows newly added concepts within <project>/specs
  - [x] Shows unimplemented steps/concepts within <project>/specs
  - [ ] Does not show steps, concepts [outside <project>/specs](https://github.com/getgauge/Intellij-Plugin/issues/184)
  - [ ] After refactoring, the [older steps are still shown](https://github.com/getgauge/Intellij-Plugin/issues/184)
- [ ] Step implementation
  - [x] Implements steps with no parameters
  - [x] Implements steps with simple parameters
  - [x] Implements steps with table parameters
  - [ ] Implements steps with special file parameters. But [the parameter name in the annotation causes refactoring issues](https://github.com/getgauge/Intellij-Plugin/issues/187)
  - [x] Implements steps with special table parameters 
  - [x] Implements steps with special characters in parameter name
    (https://github.com/getgauge/Intellij-Plugin/issues/155)
- [ ] Formatting
  - [x] Formats a simple spec
  - [x] Formats a spec with table
  - [x] Formats a spec with context, scenario steps, teardown steps
  - [x] Formats a spec with special parameters
  - [x] Formats a spec with tags and comments
  - [x] Formatting retains the spaces in between steps and inline tables
  - [ ] Formatting a spec is [removing the escape characters](https://github.com/getgauge/gauge/issues/318).
- [ ] Syntax highlighting
  - [ ] Does not highlight syntax highest spec folder is not the default folder.
  - [ ] In a spec without scenarios, [Unimplemented steps are shown as implemented]
  - [x] Highlights unimplemented step.
- [ ] Execution
  - [ ] Right click and [running a single scenario](https://waffle.io/getgauge/gauge/cards/57c3d0ca26df921d005af269) is running the entire spec 
  - [ ] Right click on a [folder without specs at highest level](https://github.com/getgauge/Intellij-Plugin/issues/188) is not showing the run sub menu 
  - [x] Able to run specs from IDE
  - [x] Able to run specs from IDE with command line parameters
  - [x] Able to run specs in parallel
- [x] Debugging
  - [x] Able to debug simple steps
  - [x] Able to debug steps with simple, table, special parameters.
  - [x] Able to debug hooks
  - [x] Able to debug hooks with parameters
- [ ] Refactoring
  - [ ] [Unable to refactor steps with COF](https://github.com/getgauge/Intellij-Plugin/issues/183)
  - [ ] [Proposed enhancements](https://github.com/getgauge/Intellij-Plugin/issues/190)
- [x] Find usages
- [x] table template

**Comment by sguptatw** [comment]
Tracking individual issues separately
